services:
  db:
    image: mariadb:10.7.3
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
      MARIADB_DATABASE: "harness"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "./data:/var/lib/mysql"
    command: "--innodb_strict_mode=OFF"
  phpmyadmin:
    image: phpmyadmin:5.1.3
    environment:
      MYSQL_ROOT_PASSWORD: ""
      PMA_USER: "root"
      PMA_PASSWORD: ""
    links:
      - db
    ports:
      - "8080:80"

